/* ___________________________________________________________________________
@ 
@ file - {{project.name}}.cpp
@ 
@ auth - yedaoq@gmail.com          http://blog.yedaoq.info
@ date - 
@ info - auto generated by yedaoq xmlschema tool
@     
/* ___________________________________________________________________________*/

#include "{{project.name}}.h"				// import the declaration of enum class


#include "CPP\XmlMapping/ParserMicro.h"		// import the parse micro template

#undef _{{project.name.upper}}_XSD_

#include "{{project.name}}.h"				// generate the parse function for type struct


#include "CPP\XmlMapping/SerialMicro.h"		// import the parse micro template

#undef _{{project.name.upper}}_XSD_

#include "{{project.name}}.h"				// generate the serialize function for type struct