/* ___________________________________________________________________________
@ 
@ file - {{project.name}}Enum.cpp
@ 
@ auth - yedaoq@gmail.com          http://blog.yedaoq.info
@ date - 
@ info - auto generated by yedaoq xmlschema tool
@     
/* ___________________________________________________________________________*/

#include "{{project.name}}Enum.h"				// import the declaration of enum class

#include "CPP\EnumDeclaration3x/EnumCppMicro.h"	// import the cpp micro template

#undef _{{project.name.upper}}_ENUM_

#include "{{project.name}}Enum.h"				// generate a Initialize function for enum class